// Code generated by MockGen. DO NOT EDIT.
// Source: rsvp_usecase.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	dto "github.com/RianIhsan/go-boilerplate-v4/internal/domain/rsvp/dto"
	pagination "github.com/RianIhsan/go-boilerplate-v4/pkg/pagination"
	gomock "github.com/golang/mock/gomock"
)

// MockRSVPUsecase is a mock of RSVPUsecase interface.
type MockRSVPUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockRSVPUsecaseMockRecorder
}

// MockRSVPUsecaseMockRecorder is the mock recorder for MockRSVPUsecase.
type MockRSVPUsecaseMockRecorder struct {
	mock *MockRSVPUsecase
}

// NewMockRSVPUsecase creates a new mock instance.
func NewMockRSVPUsecase(ctrl *gomock.Controller) *MockRSVPUsecase {
	mock := &MockRSVPUsecase{ctrl: ctrl}
	mock.recorder = &MockRSVPUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRSVPUsecase) EXPECT() *MockRSVPUsecaseMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockRSVPUsecase) GetAll(ctx context.Context, userID, invitationID string, pg pagination.Pagination) (*dto.RSVPListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, userID, invitationID, pg)
	ret0, _ := ret[0].(*dto.RSVPListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockRSVPUsecaseMockRecorder) GetAll(ctx, userID, invitationID, pg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockRSVPUsecase)(nil).GetAll), ctx, userID, invitationID, pg)
}

// Submit mocks base method.
func (m *MockRSVPUsecase) Submit(ctx context.Context, slug string, req *dto.SubmitRSVPRequest) (*dto.RSVPResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Submit", ctx, slug, req)
	ret0, _ := ret[0].(*dto.RSVPResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Submit indicates an expected call of Submit.
func (mr *MockRSVPUsecaseMockRecorder) Submit(ctx, slug, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submit", reflect.TypeOf((*MockRSVPUsecase)(nil).Submit), ctx, slug, req)
}
