// Code generated by MockGen. DO NOT EDIT.
// Source: guest_usecase.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	dto "github.com/RianIhsan/go-boilerplate-v4/internal/domain/guest/dto"
	pagination "github.com/RianIhsan/go-boilerplate-v4/pkg/pagination"
	gomock "github.com/golang/mock/gomock"
)

// MockGuestUsecase is a mock of GuestUsecase interface.
type MockGuestUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockGuestUsecaseMockRecorder
}

// MockGuestUsecaseMockRecorder is the mock recorder for MockGuestUsecase.
type MockGuestUsecaseMockRecorder struct {
	mock *MockGuestUsecase
}

// NewMockGuestUsecase creates a new mock instance.
func NewMockGuestUsecase(ctrl *gomock.Controller) *MockGuestUsecase {
	mock := &MockGuestUsecase{ctrl: ctrl}
	mock.recorder = &MockGuestUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGuestUsecase) EXPECT() *MockGuestUsecaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockGuestUsecase) Create(ctx context.Context, userID, invitationID string, req *dto.CreateGuestRequest) (*dto.GuestResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, invitationID, req)
	ret0, _ := ret[0].(*dto.GuestResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockGuestUsecaseMockRecorder) Create(ctx, userID, invitationID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGuestUsecase)(nil).Create), ctx, userID, invitationID, req)
}

// Delete mocks base method.
func (m *MockGuestUsecase) Delete(ctx context.Context, userID, invitationID, guestID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, invitationID, guestID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGuestUsecaseMockRecorder) Delete(ctx, userID, invitationID, guestID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGuestUsecase)(nil).Delete), ctx, userID, invitationID, guestID)
}

// GetAll mocks base method.
func (m *MockGuestUsecase) GetAll(ctx context.Context, userID, invitationID string, pg pagination.Pagination) (*dto.GuestListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, userID, invitationID, pg)
	ret0, _ := ret[0].(*dto.GuestListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockGuestUsecaseMockRecorder) GetAll(ctx, userID, invitationID, pg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockGuestUsecase)(nil).GetAll), ctx, userID, invitationID, pg)
}

// GetPublicByToken mocks base method.
func (m *MockGuestUsecase) GetPublicByToken(ctx context.Context, slug, token string) (*dto.PublicGuestResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicByToken", ctx, slug, token)
	ret0, _ := ret[0].(*dto.PublicGuestResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicByToken indicates an expected call of GetPublicByToken.
func (mr *MockGuestUsecaseMockRecorder) GetPublicByToken(ctx, slug, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicByToken", reflect.TypeOf((*MockGuestUsecase)(nil).GetPublicByToken), ctx, slug, token)
}
