// Code generated by MockGen. DO NOT EDIT.
// Source: filemeta_usecase.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	io "io"
	reflect "reflect"

	dto "github.com/RianIhsan/go-boilerplate-v4/internal/domain/filemeta/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockFileMetaUsecase is a mock of FileMetaUsecase interface.
type MockFileMetaUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockFileMetaUsecaseMockRecorder
}

// MockFileMetaUsecaseMockRecorder is the mock recorder for MockFileMetaUsecase.
type MockFileMetaUsecaseMockRecorder struct {
	mock *MockFileMetaUsecase
}

// NewMockFileMetaUsecase creates a new mock instance.
func NewMockFileMetaUsecase(ctrl *gomock.Controller) *MockFileMetaUsecase {
	mock := &MockFileMetaUsecase{ctrl: ctrl}
	mock.recorder = &MockFileMetaUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileMetaUsecase) EXPECT() *MockFileMetaUsecaseMockRecorder {
	return m.recorder
}

// ParseMetadata mocks base method.
func (m *MockFileMetaUsecase) ParseMetadata(ctx context.Context, file io.Reader) (*dto.FileMetadataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseMetadata", ctx, file)
	ret0, _ := ret[0].(*dto.FileMetadataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseMetadata indicates an expected call of ParseMetadata.
func (mr *MockFileMetaUsecaseMockRecorder) ParseMetadata(ctx, file interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseMetadata", reflect.TypeOf((*MockFileMetaUsecase)(nil).ParseMetadata), ctx, file)
}
