// Code generated by MockGen. DO NOT EDIT.
// Source: jwt.go

package mock

import (
	reflect "reflect"

	jwtpkg "github.com/RianIhsan/go-boilerplate-v4/pkg/jwt"
	gomock "github.com/golang/mock/gomock"
)

type MockJWTService struct {
	ctrl     *gomock.Controller
	recorder *MockJWTServiceMockRecorder
}

type MockJWTServiceMockRecorder struct {
	mock *MockJWTService
}

func NewMockJWTService(ctrl *gomock.Controller) *MockJWTService {
	mock := &MockJWTService{ctrl: ctrl}
	mock.recorder = &MockJWTServiceMockRecorder{mock}
	return mock
}

func (m *MockJWTService) EXPECT() *MockJWTServiceMockRecorder {
	return m.recorder
}

func (m *MockJWTService) GenerateToken(userID, email string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", userID, email)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockJWTServiceMockRecorder) GenerateToken(userID, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockJWTService)(nil).GenerateToken), userID, email)
}

func (m *MockJWTService) ValidateToken(token string) (*jwtpkg.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", token)
	ret0, _ := ret[0].(*jwtpkg.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockJWTServiceMockRecorder) ValidateToken(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockJWTService)(nil).ValidateToken), token)
}
