// Code generated by MockGen. DO NOT EDIT.
// Source: invitation_repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/RianIhsan/go-boilerplate-v4/internal/domain/invitation/entity"
	pagination "github.com/RianIhsan/go-boilerplate-v4/pkg/pagination"
	gomock "github.com/golang/mock/gomock"
)

// MockInvitationRepository is a mock of InvitationRepository interface.
type MockInvitationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInvitationRepositoryMockRecorder
}

// MockInvitationRepositoryMockRecorder is the mock recorder for MockInvitationRepository.
type MockInvitationRepositoryMockRecorder struct {
	mock *MockInvitationRepository
}

// NewMockInvitationRepository creates a new mock instance.
func NewMockInvitationRepository(ctrl *gomock.Controller) *MockInvitationRepository {
	mock := &MockInvitationRepository{ctrl: ctrl}
	mock.recorder = &MockInvitationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvitationRepository) EXPECT() *MockInvitationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInvitationRepository) Create(ctx context.Context, invitation *entity.Invitation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, invitation)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockInvitationRepositoryMockRecorder) Create(ctx, invitation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInvitationRepository)(nil).Create), ctx, invitation)
}

// Delete mocks base method.
func (m *MockInvitationRepository) Delete(ctx context.Context, id, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInvitationRepositoryMockRecorder) Delete(ctx, id, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInvitationRepository)(nil).Delete), ctx, id, userID)
}

// FindAllByUserID mocks base method.
func (m *MockInvitationRepository) FindAllByUserID(ctx context.Context, userID string, pg pagination.Pagination) ([]*entity.Invitation, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByUserID", ctx, userID, pg)
	ret0, _ := ret[0].([]*entity.Invitation)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAllByUserID indicates an expected call of FindAllByUserID.
func (mr *MockInvitationRepositoryMockRecorder) FindAllByUserID(ctx, userID, pg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByUserID", reflect.TypeOf((*MockInvitationRepository)(nil).FindAllByUserID), ctx, userID, pg)
}

// FindByID mocks base method.
func (m *MockInvitationRepository) FindByID(ctx context.Context, id, userID string) (*entity.Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id, userID)
	ret0, _ := ret[0].(*entity.Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockInvitationRepositoryMockRecorder) FindByID(ctx, id, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockInvitationRepository)(nil).FindByID), ctx, id, userID)
}

// FindBySlug mocks base method.
func (m *MockInvitationRepository) FindBySlug(ctx context.Context, slug string) (*entity.Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySlug", ctx, slug)
	ret0, _ := ret[0].(*entity.Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySlug indicates an expected call of FindBySlug.
func (mr *MockInvitationRepositoryMockRecorder) FindBySlug(ctx, slug interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySlug", reflect.TypeOf((*MockInvitationRepository)(nil).FindBySlug), ctx, slug)
}

// Update mocks base method.
func (m *MockInvitationRepository) Update(ctx context.Context, invitation *entity.Invitation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, invitation)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockInvitationRepositoryMockRecorder) Update(ctx, invitation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockInvitationRepository)(nil).Update), ctx, invitation)
}
