// Code generated by MockGen. DO NOT EDIT.
// Source: guest_repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/RianIhsan/go-boilerplate-v4/internal/domain/guest/entity"
	pagination "github.com/RianIhsan/go-boilerplate-v4/pkg/pagination"
	gomock "github.com/golang/mock/gomock"
)

// MockGuestRepository is a mock of GuestRepository interface.
type MockGuestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGuestRepositoryMockRecorder
}

// MockGuestRepositoryMockRecorder is the mock recorder for MockGuestRepository.
type MockGuestRepositoryMockRecorder struct {
	mock *MockGuestRepository
}

// NewMockGuestRepository creates a new mock instance.
func NewMockGuestRepository(ctrl *gomock.Controller) *MockGuestRepository {
	mock := &MockGuestRepository{ctrl: ctrl}
	mock.recorder = &MockGuestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGuestRepository) EXPECT() *MockGuestRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockGuestRepository) Create(ctx context.Context, guest *entity.Guest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, guest)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockGuestRepositoryMockRecorder) Create(ctx, guest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGuestRepository)(nil).Create), ctx, guest)
}

// Delete mocks base method.
func (m *MockGuestRepository) Delete(ctx context.Context, id, invitationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, invitationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGuestRepositoryMockRecorder) Delete(ctx, id, invitationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGuestRepository)(nil).Delete), ctx, id, invitationID)
}

// FindAllByInvitationID mocks base method.
func (m *MockGuestRepository) FindAllByInvitationID(ctx context.Context, invitationID string, pg pagination.Pagination) ([]*entity.Guest, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByInvitationID", ctx, invitationID, pg)
	ret0, _ := ret[0].([]*entity.Guest)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAllByInvitationID indicates an expected call of FindAllByInvitationID.
func (mr *MockGuestRepositoryMockRecorder) FindAllByInvitationID(ctx, invitationID, pg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByInvitationID", reflect.TypeOf((*MockGuestRepository)(nil).FindAllByInvitationID), ctx, invitationID, pg)
}

// FindByID mocks base method.
func (m *MockGuestRepository) FindByID(ctx context.Context, id, invitationID string) (*entity.Guest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id, invitationID)
	ret0, _ := ret[0].(*entity.Guest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockGuestRepositoryMockRecorder) FindByID(ctx, id, invitationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockGuestRepository)(nil).FindByID), ctx, id, invitationID)
}

// FindByToken mocks base method.
func (m *MockGuestRepository) FindByToken(ctx context.Context, token string) (*entity.Guest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByToken", ctx, token)
	ret0, _ := ret[0].(*entity.Guest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByToken indicates an expected call of FindByToken.
func (mr *MockGuestRepositoryMockRecorder) FindByToken(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByToken", reflect.TypeOf((*MockGuestRepository)(nil).FindByToken), ctx, token)
}
