// Code generated by MockGen. DO NOT EDIT.
// Source: rsvp_repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/RianIhsan/go-boilerplate-v4/internal/domain/rsvp/entity"
	pagination "github.com/RianIhsan/go-boilerplate-v4/pkg/pagination"
	gomock "github.com/golang/mock/gomock"
)

// MockRSVPRepository is a mock of RSVPRepository interface.
type MockRSVPRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRSVPRepositoryMockRecorder
}

// MockRSVPRepositoryMockRecorder is the mock recorder for MockRSVPRepository.
type MockRSVPRepositoryMockRecorder struct {
	mock *MockRSVPRepository
}

// NewMockRSVPRepository creates a new mock instance.
func NewMockRSVPRepository(ctrl *gomock.Controller) *MockRSVPRepository {
	mock := &MockRSVPRepository{ctrl: ctrl}
	mock.recorder = &MockRSVPRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRSVPRepository) EXPECT() *MockRSVPRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRSVPRepository) Create(ctx context.Context, rsvp *entity.RSVP) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, rsvp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRSVPRepositoryMockRecorder) Create(ctx, rsvp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRSVPRepository)(nil).Create), ctx, rsvp)
}

// FindAllByInvitationID mocks base method.
func (m *MockRSVPRepository) FindAllByInvitationID(ctx context.Context, invitationID string, pg pagination.Pagination) ([]*entity.RSVP, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByInvitationID", ctx, invitationID, pg)
	ret0, _ := ret[0].([]*entity.RSVP)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAllByInvitationID indicates an expected call of FindAllByInvitationID.
func (mr *MockRSVPRepositoryMockRecorder) FindAllByInvitationID(ctx, invitationID, pg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByInvitationID", reflect.TypeOf((*MockRSVPRepository)(nil).FindAllByInvitationID), ctx, invitationID, pg)
}

// FindByGuestID mocks base method.
func (m *MockRSVPRepository) FindByGuestID(ctx context.Context, guestID string) (*entity.RSVP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByGuestID", ctx, guestID)
	ret0, _ := ret[0].(*entity.RSVP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByGuestID indicates an expected call of FindByGuestID.
func (mr *MockRSVPRepositoryMockRecorder) FindByGuestID(ctx, guestID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByGuestID", reflect.TypeOf((*MockRSVPRepository)(nil).FindByGuestID), ctx, guestID)
}

// Update mocks base method.
func (m *MockRSVPRepository) Update(ctx context.Context, rsvp *entity.RSVP) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, rsvp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRSVPRepositoryMockRecorder) Update(ctx, rsvp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRSVPRepository)(nil).Update), ctx, rsvp)
}
