// Code generated by MockGen. DO NOT EDIT.
// Source: invitation_usecase.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	dto "github.com/RianIhsan/go-boilerplate-v4/internal/domain/invitation/dto"
	pagination "github.com/RianIhsan/go-boilerplate-v4/pkg/pagination"
	gomock "github.com/golang/mock/gomock"
)

// MockInvitationUsecase is a mock of InvitationUsecase interface.
type MockInvitationUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockInvitationUsecaseMockRecorder
}

// MockInvitationUsecaseMockRecorder is the mock recorder for MockInvitationUsecase.
type MockInvitationUsecaseMockRecorder struct {
	mock *MockInvitationUsecase
}

// NewMockInvitationUsecase creates a new mock instance.
func NewMockInvitationUsecase(ctrl *gomock.Controller) *MockInvitationUsecase {
	mock := &MockInvitationUsecase{ctrl: ctrl}
	mock.recorder = &MockInvitationUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvitationUsecase) EXPECT() *MockInvitationUsecaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInvitationUsecase) Create(ctx context.Context, userID string, req *dto.CreateInvitationRequest) (*dto.InvitationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, req)
	ret0, _ := ret[0].(*dto.InvitationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockInvitationUsecaseMockRecorder) Create(ctx, userID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInvitationUsecase)(nil).Create), ctx, userID, req)
}

// Delete mocks base method.
func (m *MockInvitationUsecase) Delete(ctx context.Context, id, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInvitationUsecaseMockRecorder) Delete(ctx, id, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInvitationUsecase)(nil).Delete), ctx, id, userID)
}

// GetAll mocks base method.
func (m *MockInvitationUsecase) GetAll(ctx context.Context, userID string, pg pagination.Pagination) (*dto.InvitationListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, userID, pg)
	ret0, _ := ret[0].(*dto.InvitationListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockInvitationUsecaseMockRecorder) GetAll(ctx, userID, pg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockInvitationUsecase)(nil).GetAll), ctx, userID, pg)
}

// GetByID mocks base method.
func (m *MockInvitationUsecase) GetByID(ctx context.Context, id, userID string) (*dto.InvitationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id, userID)
	ret0, _ := ret[0].(*dto.InvitationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockInvitationUsecaseMockRecorder) GetByID(ctx, id, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockInvitationUsecase)(nil).GetByID), ctx, id, userID)
}

// GetPublicBySlug mocks base method.
func (m *MockInvitationUsecase) GetPublicBySlug(ctx context.Context, slug string) (*dto.PublicInvitationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicBySlug", ctx, slug)
	ret0, _ := ret[0].(*dto.PublicInvitationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicBySlug indicates an expected call of GetPublicBySlug.
func (mr *MockInvitationUsecaseMockRecorder) GetPublicBySlug(ctx, slug interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicBySlug", reflect.TypeOf((*MockInvitationUsecase)(nil).GetPublicBySlug), ctx, slug)
}

// Update mocks base method.
func (m *MockInvitationUsecase) Update(ctx context.Context, id, userID string, req *dto.UpdateInvitationRequest) (*dto.InvitationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, userID, req)
	ret0, _ := ret[0].(*dto.InvitationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockInvitationUsecaseMockRecorder) Update(ctx, id, userID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockInvitationUsecase)(nil).Update), ctx, id, userID, req)
}
